/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo_m14_5210411292;
import javax.swing.JOptionPane;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
/**
 *
 * @author kicol
 */
public class ITWorkerForm extends javax.swing.JFrame {
    private Connection db;
    private DefaultTableModel model;
    /**
     * Creates new form ITWorkerForm
     */
    public ITWorkerForm() {
        initComponents();
        db = KoneksiDB.getKoneksi();
        model = (DefaultTableModel) tablePegawai.getModel();
        this.loadToTable();
        
    }

    private void loadToTable(){
        model.setRowCount(0);
        
        try{
            db = KoneksiDB.getKoneksi();
            Statement st = db.createStatement();
            
            String sql = "SELECT * FROM pegawai";
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                Object[] data = new Object[7];
                data[0] = rs.getString("nama");
                data[1] = rs.getString("noPegawai");
                data[2] = rs.getString("posisi");
                data[3] = rs.getString("gaji");
                data[4] = rs.getInt("id");
                
                model.addRow(data);
            }
            rs.close();
            st.close();
        }catch(SQLException e){
            System.err.println("load data error : "+ e.getMessage());
        }finally{
            txtID.setEnabled(false);
            txtGaji.setText("15.000.000");
            txtGaji.setEnabled(false);
            tablePegawai.getColumnModel().getColumn(4).setMinWidth(0);
            tablePegawai.getColumnModel().getColumn(4).setMaxWidth(0);
        }
    }
    
     public void printall()throws NamaDanNoPegawaiHarusDiisi,NoPegawaiHarusAngka,NoPegawaiHarus10Digit{
        if(txtNama.getText().isEmpty()|| txtNoPegawai.getText().isEmpty()){
            throw new NamaDanNoPegawaiHarusDiisi();
        }try{
            Long.parseLong(txtNoPegawai.getText());
        }catch(NumberFormatException e){
            throw new NoPegawaiHarusAngka();
        }if (txtNoPegawai.getText().length() != 10){
            throw new NoPegawaiHarus10Digit();
        }      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bttnExit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtNoPegawai = new javax.swing.JTextField();
        cmbPosisi = new javax.swing.JComboBox<>();
        txtGaji = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePegawai = new javax.swing.JTable();
        bttnUpdate = new javax.swing.JButton();
        bttnDelete = new javax.swing.JButton();
        bttnInsert = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("IT Worker Form");

        bttnExit.setBackground(java.awt.Color.red);
        bttnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bttnExit.setText("Exit");
        bttnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnExitActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("No. Pegawai");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Posisi");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Gaji (IDR)");

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        cmbPosisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Senior Programmer", "Bussiness Analyst", "Data Center Officer", "Junior Programmer" }));
        cmbPosisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPosisiActionPerformed(evt);
            }
        });

        tablePegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama", "No. Pegawai", "Posisi", "Gaji (IDR)", "id"
            }
        ));
        tablePegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePegawaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePegawai);

        bttnUpdate.setBackground(java.awt.Color.blue);
        bttnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bttnUpdate.setText("Update");
        bttnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnUpdateActionPerformed(evt);
            }
        });

        bttnDelete.setBackground(java.awt.Color.yellow);
        bttnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bttnDelete.setText("Delete");
        bttnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnDeleteActionPerformed(evt);
            }
        });

        bttnInsert.setBackground(java.awt.Color.green);
        bttnInsert.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bttnInsert.setText("Insert");
        bttnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnInsertActionPerformed(evt);
            }
        });

        txtID.setText("jTextField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(110, 110, 110)
                                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNoPegawai, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                                    .addComponent(cmbPosisi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtGaji)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(bttnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bttnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bttnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(bttnExit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNoPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbPosisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnUpdate)
                    .addComponent(bttnInsert))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bttnExitActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void bttnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnUpdateActionPerformed
        // TODO add your handling code here:
        try{
            this.printall();
        }catch(NoPegawaiHarusAngka e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());    
        } catch (NamaDanNoPegawaiHarusDiisi e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }catch (NoPegawaiHarus10Digit e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        
        try {
            db = KoneksiDB.getKoneksi();

            String sql = "UPDATE pegawai "
                    + "SET nama=?, noPegawai=?, posisi=?, gaji=? WHERE id=?;";

            PreparedStatement ps = db.prepareStatement(sql);

            ps.setString(1, txtNama.getText());
            ps.setString(2, txtNoPegawai.getText());
            ps.setString(3, cmbPosisi.getSelectedItem().toString());
            ps.setString(4, txtGaji.getText());
            ps.setString(5, txtID.getText());
            
            int rowInsert = ps.executeUpdate();
            if (rowInsert > 0) {
                JOptionPane.showMessageDialog(this, "Data Successfully Updated", "Success", JOptionPane.INFORMATION_MESSAGE);
            }

            ps.close();
               
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Data Failed to Update", "Error", JOptionPane.ERROR_MESSAGE);
        }
        finally {
            this.loadToTable();
        }
       
    }//GEN-LAST:event_bttnUpdateActionPerformed

    private void bttnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            db = KoneksiDB.getKoneksi();

            String sql = "DELETE FROM pegawai "
                    + "WHERE id=?;";

            PreparedStatement ps = db.prepareStatement(sql);

            ps.setString(1, txtID.getText());

            int rowInsert = ps.executeUpdate();
            if (rowInsert > 0) {
                JOptionPane.showMessageDialog(this, "Data Successfully Deleted", "Success", JOptionPane.INFORMATION_MESSAGE);
            }

            ps.close();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Failed to Delete", "Error", JOptionPane.ERROR_MESSAGE);
        }
        finally {
            this.loadToTable();
            txtNama.setText("");
            txtNoPegawai.setText("");
            cmbPosisi.setSelectedIndex(0);
            txtGaji.setText("15.000.000");
            txtGaji.setEnabled(false);
        }
    }//GEN-LAST:event_bttnDeleteActionPerformed

    private void bttnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnInsertActionPerformed
        // TODO add your handling code here:
        try{
            this.printall();
        }catch(NoPegawaiHarusAngka e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());    
        } catch (NamaDanNoPegawaiHarusDiisi e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }catch (NoPegawaiHarus10Digit e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        
        try {
            db = KoneksiDB.getKoneksi();

            String sql = "INSERT INTO pegawai "
                    + "(nama,noPegawai,posisi,gaji) "
                    + "VALUES (?,?,?,?)";

            PreparedStatement ps = db.prepareStatement(sql);

            ps.setString(1, txtNama.getText());
            ps.setString(2, txtNoPegawai.getText());
            ps.setString(3, cmbPosisi.getSelectedItem().toString());
            ps.setString(4, txtGaji.getText());

            int rowInsert = ps.executeUpdate();
            if (rowInsert > 0) {
                JOptionPane.showMessageDialog(this, "Data Successfully Inserted", "Success", JOptionPane.INFORMATION_MESSAGE);
            }

            ps.close();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Failed to Insert", "Error", JOptionPane.ERROR_MESSAGE);
        }
        finally {
            this.loadToTable();
        }
    }//GEN-LAST:event_bttnInsertActionPerformed

    private void cmbPosisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPosisiActionPerformed
        // TODO add your handling code here:
        if(cmbPosisi.getSelectedIndex() == 0){
            txtGaji.setText("15.000.000");
            txtGaji.setEnabled(false);
        }else if(cmbPosisi.getSelectedIndex() == 1){
            txtGaji.setText("21.000.000");
            txtGaji.setEnabled(false);
        }else if(cmbPosisi.getSelectedIndex() == 2){
            txtGaji.setText("18.000.000");
            txtGaji.setEnabled(false);
        }else if(cmbPosisi.getSelectedIndex() == 3){
            txtGaji.setText("8.000.000");
            txtGaji.setEnabled(false);
        }
    }//GEN-LAST:event_cmbPosisiActionPerformed

    private void tablePegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePegawaiMouseClicked
        // TODO add your handling code here:
        int rowIdx = tablePegawai.getSelectedRow();

        String nama = tablePegawai.getValueAt(rowIdx, 0).toString();
        txtNama.setText(nama);

        String no = tablePegawai.getValueAt(rowIdx, 1).toString();
        txtNoPegawai.setText(no);

        String posisi = tablePegawai.getValueAt(rowIdx, 2).toString();
        switch (posisi) {
            case "Senior Programmer":
                cmbPosisi.setSelectedIndex(0);
                txtGaji.setText("15.000.000");
                break;
            case "Bussiness Analyst":
                cmbPosisi.setSelectedIndex(1);
                txtGaji.setText("21.000.000");
                break;
            case "Data Office Center":
                cmbPosisi.setSelectedIndex(2);
                txtGaji.setText("18.000.000");
                break;
            case "Junior Programmer":
                cmbPosisi.setSelectedIndex(3);
                txtGaji.setText("8.000.000");
                break;
        }
        
        String id = tablePegawai.getValueAt(rowIdx, 4).toString();
        txtID.setText(id);
        
    }//GEN-LAST:event_tablePegawaiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ITWorkerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ITWorkerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ITWorkerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ITWorkerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ITWorkerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnDelete;
    private javax.swing.JButton bttnExit;
    private javax.swing.JButton bttnInsert;
    private javax.swing.JButton bttnUpdate;
    private javax.swing.JComboBox<String> cmbPosisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tablePegawai;
    private javax.swing.JTextField txtGaji;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoPegawai;
    // End of variables declaration//GEN-END:variables
}
